<meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo App::config("nazivApp") ?></title>
    <link rel="stylesheet" href="<?php echo App::config("url") ?>public/css/foundation.css">
    <!--<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">-->
    <link rel="stylesheet" href="<?php echo App::config("url") ?>public/css/app.css">
    <link rel="stylesheet" href="public/fontawesome/css/all.min.css">
    <!-- <script defer src="https://use.fontawesome.com/releases/v5.7.0/js/all.js" integrity="sha384-qD/MNBVMm3hVYCbRTSOW130+CWeRIKbpot9/gR1BHkd7sIct4QKhT1hOPd+2hO8K" crossorigin="anonymous"></script>-->
    <link rel="shortcut icon" href="<?php echo App::config("url") ?>public/favicon.ico" type="image/x-icon">