<div class="grid-x">
<div class="large-12 medium-12 small-12 columns">
<ul class="vertical medium-horizontal menu" data-responsive-menu="accordion medium-dropdown">
  <li>
    <a href="<?php echo App::config("url")."index" ?>">Početna</a>
    
  </li>
  <li>
    <a href="<?php echo App::config("url")."onama" ?>">O nama</a>
    
  </li>
  <li>
    <a href="<?php echo App::config("url")."kontakt" ?>">Kontakt</a>
    
  </li>
</ul>
<div class="top-bar-right">
<ul class="menu">
    <li>login</li>
</ul>
</div>
</div>
</div>